### ISSUE TITLE
Python Version Ubtunu 16.04 VPS

### ISSUE THREAD

**Issue by Caddyrn** [deluxghost/simple-asf-bot#2]
Hey, i get this Error with your Script :( 

a
root@:/home/Archisteamfarm/config/TeleBot# python bot.py
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    import ASF_IPC as asf
  File "/usr/local/lib/python2.7/dist-packages/ASF_IPC/__init__.py", line 139
    async def start_log(self):
            ^
SyntaxError: invalid syntax
root@:/home/Archisteamfarm/config/TeleBot# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    import ASF_IPC as asf
  File "/usr/local/lib/python3.5/dist-packages/ASF_IPC/__init__.py", line 159

     ^
SyntaxError: 'yield' inside async function
root@h2777498:/home/Archisteamfarm/config/TeleBot#

**Comment by deluxghost** [comment]
in the latest version, this bot needs python 3.6 or above to run. because the ASF-IPC lib needs that.

ASF-IPC needs python 3.6+ because it should support the new dynamic /Api/Log api of ASF

tgbot will also support logs sometime but i'm not sure
